name: Upload files into FC on manual trigger (supports both create and update)

on:
  workflow_dispatch:
    inputs:
      folder_to_upload:
        description: "Folder to upload .ttl files from (e.g., 'vehicle_model')"
        required: true
        type: string
      dry_run:
        description: "Dry Run (no changes will be made to FC)"
        required: true
        default: true
        type: boolean

env:
  # 'inputs' context is cleaner than 'github.event.inputs'
  FOLDER_TO_UPLOAD: ${{ inputs.folder_to_upload }}
  DRY_RUN: ${{ inputs.dry_run }}
  KEYCLOAK_USER: ${{ secrets.KEYCLOAK_USER }}
  KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
  KEYCLOAK_CLIENT_SECRET_KEY: ${{ secrets.KEYCLOAK_CLIENT_SECRET_KEY }}

jobs:
  upload-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        # Installs packages like keycloak_client, requests, etc. from pyproject.toml
        run: pip install -e .
      - name: Run Python upload into FC
        run: python3 -m src.tools.uploaders.fc_upload_with_update
